# Generated by Django 3.0.6 on 2020-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
