# Generated by Django 3.0.6 on 2020-06-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_queries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queries',
        ),
    ]
