# Generated by Django 3.0.6 on 2020-06-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
