# Generated by Django 3.0.6 on 2020-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
